version: '2'
services:
  datos:
    image: busybox
    volumes:
      - .:/app
  redis:
    image: redis
    ports:
      - 6379:6379
    volumes:
        - ./config/redis.conf:/redis.conf
    command: [ "redis-server", "/redis.conf" ]
    # expose:
    #   - "6378"
  colegio_entrevista:
    build:
      context: ./docker
    volumes_from:
      - datos
    ports:
        - "5000:5000"
    expose:
      - "5000"
    links:
      - redis:redis
      - mysql:mysql
    environment:
      MYSQL_HOST: mysql
      MYSQL_USER: root
      MYSQL_PASSWORD: password
      MYSQL_DB: colegio_entrevista
    depends_on:
      - datos
      - redis
      - mysql
  mysql:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'colegio_entrevista'
      MYSQL_USER: 'root1'
      MYSQL_PASSWORD: 'password1'
      MYSQL_ROOT_PASSWORD: 'password1'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - ./my-db:/var/lib/mysql